# Configurations
title: Lucas Cruz
longtitle: Lucas Cruz
author: Lucas Cruz
email: lucas@lucas-cruz.com
description: >
  A blog where I dive into my research and discuss topics like experimentation, causal inference, reinforcement learning, and robotics.

version: 1.0
gitbook_version: 3.2.3

url: "https://lucas-cruz.com"
baseurl: ""
rss: RSS

github_username: cruz-lucas
twitter_username: _Lucas_Cruz

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 1

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}/favicon.ico
favicon_path: assets/images/favicon

# markdown render engine.
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  math_engine: mathjax
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..2
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true

syntax_highlighter_style: colorful

markdown_ext: markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink: /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/
    weight: 1
  ml:
    name: General Machine Learning
    output: true
    permalink: /:collection/:path/
    weight: 2
  rl:
    name: Reinforcement Learning
    output: true
    permalink: /:collection/:path/
    weight: 3
  stats:
    name: Statistics
    output: true
    permalink: /:collection/:path/
    weight: 4

collections_dir: collections

page_width: 800px

destination: ./_site
incremental: false
regenerate: true

plugins:
  - jekyll-feed
  - jekyll-readme-index

tracker:
  google_analytics: G-MS3FF7B6JV
