# Configurations
title:            IMTechEd
longtitle:        IMTechEd
author:           J. Austin Straley, DO
email:            jzstraley@gmail.com
description: >
  A website detailing my past, present, and future work.

version:          1.0
gitbook_version:  3.2.3

url:              'www.imteched.com'
baseurl:          ''
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji

social_links:
  - { platform: CAMC,           user_url: "https://www.camcmedicine.edu/academic-departments/department-internal-medicine/internal-medicine-residency-program/our-current"}
  - { platform: facebook,       user_url: "https://www.facebook.com/Straley/" }
  - { platform: github,         user_url: "https://github.com/jzstraley" }
  - { platform: google_scholar, user_url: "" }
  - { platform: instagram,      user_url: "" }
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jamesstraley" }
  - { platform: orcid,          user_url: "https://orcid.org/0000-0002-5441-9515" }
  - { platform: pinterest,      user_url: "" }
  - { platform: twitter,        user_url: "" }
  - { platform: youtube,        user_url: "https://www.youtube.com/channel/UCAAanG5A04oCXc2JnTjjLRQ" }