# Configurations
title:            Jeff Kantarek
longtitle:        Jeff Kantarek - Human built with mostly AI, some real world experience
author:           Jeff Kantarek
email:            jeff.kantarek@gmail.com
description: >
  Personal blog and idea dumping ground

version:          1.0
gitbook_version:  3.2.3

url:              'https://jkantarek.github.io'
baseurl:          ''
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

github_username: jkantarek
gitlab_username: jkantarek
linkedin_username: jkantarek

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

excerpt_separator: "<!--more-->"

readme_index:
  enabled:          false
  remove_originals: false
  with_frontmatter: false

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
